# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: dfouquet <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/04/12 19:17:16 by dfouquet          #+#    #+#              #
#    Updated: 2017/10/02 17:24:03 by atgerard         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a

SRC = ft_memset.c \
	  ft_bzero.c \
	  ft_memcpy.c \
	  ft_memccpy.c \
	  ft_memmove.c \
	  ft_memchr.c \
	  ft_memcmp.c \
	  ft_strlen.c \
	  ft_strdup.c \
	  ft_strcpy.c \
	  ft_strncpy.c \
	  ft_strcat.c \
	  ft_strncat.c \
	  ft_strlcat.c \
	  ft_strchr.c \
	  ft_strrchr.c \
	  ft_strstr.c \
	  ft_strnstr.c \
	  ft_strcmp.c \
	  ft_strncmp.c \
	  ft_atoi.c \
	  ft_isalpha.c \
	  ft_isdigit.c \
	  ft_isalnum.c \
	  ft_isascii.c \
	  ft_isprint.c \
	  ft_toupper.c \
	  ft_tolower.c \
	  ft_memalloc.c \
	  ft_memdel.c \
	  ft_strnew.c \
	  ft_strdel.c \
	  ft_strclr.c \
	  ft_striter.c \
	  ft_striteri.c \
	  ft_strmap.c \
	  ft_strmapi.c \
	  ft_strequ.c \
	  ft_strnequ.c \
	  ft_strsub.c \
	  ft_strjoin.c \
	  ft_strtrim.c \
	  ft_nb_words.c \
	  ft_len_split_word.c \
	  ft_fill_word.c \
	  ft_strsplit.c \
	  ft_excep_itoa.c \
	  ft_recur_power.c \
	  ft_itoa.c \
	  ft_putchar.c \
	  ft_putstr.c \
	  ft_putendl.c \
	  ft_putnbr.c \
	  ft_putchar_fd.c \
	  ft_putstr_fd.c \
	  ft_putendl_fd.c \
	  ft_putnbr_fd.c \
	  ft_putnbr_octal.c \
	  ft_putlong_X.c \
	  ft_putnbr_X.c \
	  ft_putlong_long_X.c \
	  ft_putlong_long_x_low.c \
	  ft_memdup.c \
	  ft_lstnew.c \
	  ft_lstdelone.c \
	  ft_lstdel.c \
	  ft_lstadd.c \
	  ft_lstiter.c \
	  ft_lstmap.c \
	  bin_to_deci.c \
	  ft_itoa_base.c \
	  ft_itoa_base_long.c \
	  ft_itoa_base_majuscule.c \
	  ft_itoa_base_majuscule_long.c \
	  ft_itoa_long.c \
	  ft_recur_power_long.c \
	  ft_putshort.c \
	  ft_putsigned_char.c \
	  ft_putlong.c \
	  ft_putlong_long.c \
	  ft_putlong_x_low.c \
	  ft_putintmax_t.c \
	  ft_putssize_t.c \
	  ft_putunsigned_long.c \
	  ft_putunsigned_long_long.c \
	  ft_putsize_t.c \
	  ft_putlong_x_low_wp.c \
	  ft_putascii.c \

OBJ = ft_memset.o \
	  ft_bzero.o \
	  ft_memcpy.o \
	  ft_memccpy.o \
	  ft_memmove.o \
	  ft_memchr.o \
	  ft_memcmp.o \
	  ft_strlen.o \
	  ft_strdup.o \
	  ft_strcpy.o \
	  ft_strncpy.o \
	  ft_strcat.o \
	  ft_strncat.o \
	  ft_strlcat.o \
	  ft_strchr.o \
	  ft_strrchr.o \
	  ft_strstr.o \
	  ft_strnstr.o \
	  ft_strcmp.o \
	  ft_strncmp.o \
	  ft_atoi.o \
	  ft_isalpha.o \
	  ft_isdigit.o \
	  ft_isalnum.o \
	  ft_isascii.o \
	  ft_isprint.o \
	  ft_toupper.o \
	  ft_tolower.o \
	  ft_memalloc.o \
	  ft_memdel.o \
	  ft_strnew.o \
	  ft_strdel.o \
	  ft_strclr.o \
	  ft_striter.o \
	  ft_striteri.o \
	  ft_strmap.o \
	  ft_strmapi.o \
	  ft_strequ.o \
	  ft_strnequ.o \
	  ft_strjoin.o \
	  ft_strsub.o \
	  ft_strtrim.o \
	  ft_nb_words.o \
	  ft_len_split_word.o \
	  ft_fill_word.o \
	  ft_strsplit.o \
	  ft_excep_itoa.o \
	  ft_recur_power.o \
	  ft_recur_power_long.o \
	  ft_itoa.o \
	  ft_itoa_long.o \
	  ft_putchar.o \
	  ft_putstr.o \
	  ft_putendl.o \
	  ft_putnbr.o \
	  ft_putchar_fd.o \
	  ft_putstr_fd.o \
	  ft_putendl_fd.o \
	  ft_putnbr_fd.o \
	  ft_putnbr_octal.o \
	  ft_putlong_X.o \
	  ft_putnbr_X.o \
	  ft_putlong_long_X.o \
	  ft_putlong_long_x_low.o \
	  ft_memdup.o \
	  ft_lstnew.o \
	  ft_lstdelone.o \
	  ft_lstdel.o \
	  ft_lstadd.o \
	  ft_lstiter.o \
	  ft_lstmap.o \
	  bin_to_deci.o \
	  ft_itoa_base.o \
	  ft_itoa_base_long.o \
	  ft_itoa_base_majuscule.o \
	  ft_itoa_base_majuscule_long.o \
	  ft_putshort.o \
	  ft_putsigned_char.o \
	  ft_putlong.o \
	  ft_putlong_long.o \
	  ft_putintmax_t.o \
	  ft_putssize_t.o \
	  ft_putunsigned_long.o \
	  ft_putunsigned_long_long.o \
	  ft_putsize_t.o \
	  ft_putlong_x_low.o \
	  ft_putlong_x_low_wp.o \
	  ft_putascii.o \

all: $(NAME)

$(NAME):
	@gcc -Wall -Wextra -Werror -c $(SRC)
	@ar rc $(NAME) $(OBJ)
	@ranlib $(NAME)

clean:
	@rm -f $(OBJ)

fclean: clean
	@rm -f $(NAME)

re: fclean $(NAME)

reclean: re
	@rm -f $(OBJ)
